// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `Amount`, `Dates`, `Descriptions`, `INCOME`, `OUTCOME`, `RESULT`, `Transaction`, `Types`, `ValueDetail`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `deref`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `initialize`, `initialize`, `initialize`

void initApp() => RustLib.instance.api.crateApiSimpleInitApp();

Future<void> intialize() => RustLib.instance.api.crateApiSimpleIntialize();

void loadTransactionsFromFile({required String filePath}) =>
    RustLib.instance.api
        .crateApiSimpleLoadTransactionsFromFile(filePath: filePath);

Future<void> pushTransactionToResult(
        {required VecDequeSpent result, required TransactionsData data}) =>
    RustLib.instance.api
        .crateApiSimplePushTransactionToResult(result: result, data: data);

List<Spent> getSpentList() => RustLib.instance.api.crateApiSimpleGetSpentList();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Spent>>
abstract class Spent implements RustOpaqueInterface {
  double get amount;

  NaiveDate get date;

  String get reason;

  set amount(double amount);

  set date(NaiveDate date);

  set reason(String reason);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransactionsData>>
abstract class TransactionsData implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VecDeque < Spent >>>
abstract class VecDequeSpent implements RustOpaqueInterface {}
