name: full_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  date_field: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  flutter_rust_bridge: 2.4.0
  carousel_slider: ^5.0.0
  ffi: ^2.0.0
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9
  provider: ^6.0.0
  json_annotation: ^4.7.0
  oauth2: ^2.0.0
  url_launcher: ^6.0.17
  http: ^1.2.2 
  flutter_dotenv: ^5.0.2
  webview_flutter: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12 
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - .env